### ISSUE TITLE
Causing camelcamelcamel to darken

### ISSUE THREAD

**Issue by vertigo220** [Mr-VincentW/PhotoShow#196] opened 2024-11-29 03:54 UTC
When this is active for camelcamelcamel dot com and the price tracking graph is hovered over, it causes the entire page to darken like a filter is over it. It gives the impression like there's a pop-up that needs to be closed, but that's not the case. Disabling the addon for that site makes the problem go away, so it's definitely PhotoShow causing it.

**Comment by Mr-VincentW** [comment] 2024-11-29 04:06
Thanks a lot for reporting the issue! It is caused by a generic styling settings from this site. However, PhotoShow will fix it with its next release, you'll be updated soon!

**Comment by Mr-VincentW** [comment] 2024-12-01 12:56
This issue has been resolved in update 4.54.0. Please wait for the app stores to complete their review process before the new release becomes available for your browser. Cheers!

**Closed as completed by Mr-VincentW** 2024-12-01 12:56 UTC
