### ISSUE TITLE
[Solved] Flickr - Some thumbnails can't be previewed

### ISSUE THREAD

**Issue by decembre** [Mr-VincentW/PhotoShow#142] opened 2024-03-10 11:47 UTC
There are problem for Flickr, by example:

**1 - It Fail on the "Square view" of the "Admin view" (not in BETA view).**
https://www.flickr.com/groups/portrait_face/pool/?thumb=1

Yes, difficult for you to see if you don't use Flickr and not Admin a pool.
If it can help, i can give to you the CSS selectors you need.
:-)
Note:
If i use my Userscript, PhotoShow work perfectly:
<a href="https://greasyfork.org/fr/scripts/483403-flickr-widescreen-bigone-pool-small-view-hi-res-pics-v-1">Flickr WideScreen BigONE - POOL Small View HI-RES Pics</a>

**2 - Problem to on the User Contact/ Follow page.**
By example:
https://www.flickr.com/people/140625004@N05/contacts/

A - PhotoShow preview the arrow near the buddy icon (top / right)

B -  But don't preview thumbnails provided by an userscript i use,
with ViolentMonkey, because it don't work with Tampermonkey - i don't know  why:
<a href="https://pastebin.com/07LpdKpW">Flickr Buddy Interesting - MATCH - TWEAK 2020 - NO TAMPERMONKEY (Why?) / OK VIOLENTMONKEY</a>
It show, after clicking the arrow near the Buddy icon,  in a popup the most interesting shot of the user
Maybe for use it you need install my userstyles (with Stylus),
Because its "interesting" button is not visible  without it (here too i don't know why)
<a href="https://userstyles.world/style/248/flickr-widescreen-bigone-v-248-usw">Flickr WideScreen - BigONE v.248 (USw)</a>

Here too, if it can help, i can give to you the CSS selectors you need.

**3 - How to not preview Buddy icons on Flickr ?**

**Comment by decembre** [comment] 2024-03-10 16:48
4 - the mini-thumbnails, another Flickr thumbnail which not work,
or Preview just one shot and after nothing ,
or preview always the same shot when i want preview another shot...

That the mini-thumbnails in the Photo page under the Photo.
Example:
https://www.flickr.com/photos/186574538@N05/51571111279/in/pool-portrait_face|186574538@N05

**Comment by Mr-VincentW** [comment] 2024-03-12 08:32
Hi, thanks again for your feedback.

The 1st (square view) and the 4th (mini-thumbnails) issues can be solved and will be fixed by the next PhotoShow update. However, I didn't manage to figure out what other issues are referring to. What is the "buddy icon" please? It would be helpful if you could attach some screenshots. Thanks.

**Comment by decembre** [comment] 2024-03-12 11:05
Thanks for your attention
:-)

Some screenshots:

**- About "2 - Problem on the User Contact/ Follow page."**
Test Link:
https://www.flickr.com/people/140625004@N05/contacts/

_A - PhotoShow preview the arrow near the buddy icon (top / right)_
Pb for unwanted preview of some interface element.

Here for Arrow near Avatar :
![2 - Problem to on the User Contact - Follow page - PB Arrows](https://github.com/Mr-VincentW/PhotoShow/assets/868778/06fa74cd-63cc-4f18-8738-67db2e9821be)

_B - But don't preview thumbnails provided by the userscript "Flickr Buddy Interesting"_
![2 - Problem to on the User Contact - Follow page - Interesting PopUp](https://github.com/Mr-VincentW/PhotoShow/assets/868778/71132fc8-aae9-4848-b087-be10ac2c0b1d)

Here the HTML of the popup:
![2 - Problem to on the User Contact - Follow page - Intersting HTML](https://github.com/Mr-VincentW/PhotoShow/assets/868778/cd5e4b01-3f6f-4536-a5e2-f3ebdfc8daa7)


- About "3 - How to not preview Buddy icons on Flickr ?":
Here for Buddy icon /Avatar (in all the site):
![2 - Problem to on the User Contact - Follow page - PB Buddy Avatar](https://github.com/Mr-VincentW/PhotoShow/assets/868778/3b3df5ca-f3b2-4eec-b3c9-682d40b03e3d)

**Comment by decembre** [comment] 2024-03-12 11:13
Maybe it can help...
From an Discussion in the pool "Flickr Hacks":
<a href="https://www.flickr.com/groups/flickrhacks/discuss/72157721920375928/#comment72157721920384567">Find the original poster of a link like https://live.staticflickr.com/XXXXXXXXX-z.jpg [In Flickr Hacks]</a>

Flickr can serve the same images in 3 different format:
[farm3.static.flickr.com/2085/2177060015_258bcfaff9_m.jpg](https://farm3.static.flickr.com/2085/2177060015_258bcfaff9_m.jpg)
[farm3.staticflickr.com/2085/2177060015_258bcfaff9_m.jpg](https://farm3.staticflickr.com/2085/2177060015_258bcfaff9_m.jpg)
[live.staticflickr.com/2085/2177060015_258bcfaff9_m.jpg](https://live.staticflickr.com/2085/2177060015_258bcfaff9_m.jpg)

**Comment by decembre** [comment] 2024-03-23 10:11
I do some test with CSS to hide certain unwanted preview image.

Here my code:

/* ==== 00 - PhotoShow Adaptation - FlickR  ==== */


/* ALL - SUPP */

/* BUDDY ARROW */
#photoShowViewer img[src*="personmenu_down_"] ,

/* BUDDY ICON */
#photoShowViewer img[src*="/buddyicons/"] ,

/* POOL - PHOTO COVER */
#photoShowViewer img[src*="/coverphoto/"] ,

/* GM BASE64 - Scroll to to Bottom by Midpoint */
#photoShowViewer img[src*="data:image/png;base64,iVBORw0KGg"]  {
  display: none  !important;
}


/* ALL - VIEWER TRANSPARENT */
#photoShowViewer {
  -webkit-backdrop-filter: unset !important;
  backdrop-filter: unset !important;
  background: transparent !important;
  border: none !important;
  border-radius: 1px;
  box-shadow: none !important;
  box-sizing: border-box;
}
#photoShowViewer .photoshow-viewer-shadow {
  background: transparent !important;
  clip-path: unset !important;
}

Not perfect but work:
When i "display: none;" these images, 
i need to make the viewer transparent,
because i see its background and shadows with no image in it.

Another thing i notice:
the option "copy address of the HD image" in the right click context menu seems not working...

**Comment by decembre** [comment] 2024-03-23 10:36
Better luck with the CSS selector :has()...
i can delete the Preview box of unwanted images preview, without affecting the other.

Little Problem:
 :has() is not supported by older browser.

Here the test:

/* ==== 00 - PhotoShow Adaptation :has()- FlickR  ==== */

/* ALL - SUPP VIEWER FOR CERTAIN IMAGES */

/* BUDDY */
#photoShowViewer:has(img[src*="/buddyicons/"]) ,

/* BUDDY ARROW */
#photoShowViewer:has(img[src*="personmenu_down_"]) ,

/* POLL - PHOTO COVER */
#photoShowViewer:has(img[src*="/coverphoto/"]) ,

/* GM BASE64 - Scroll to to Bottom by Midpoint */
#photoShowViewer:has([src*="data:image/png;base64,iVBORw0KGg"]) {
  display: none  !important;
}

**Comment by Mr-VincentW** [comment] 2024-03-24 10:11
Thanks for all the further attachments. I have made the following updates to PhotoShow in version 4.33.0.

**1. For Issue 2A:**
Unfortunately, there's no easy way to solve this issue in PhotoShow at the moment. Additionally, it's a bad practice for Flickr to use an img element as a button which breaks the HTML semantics requirement.

**2. For Issue 2B:** 
PhotoShow managed to start working on this "Flickr Buddy Interesting" image list, however, the HD images it provides here are not the largest ones as what can be done on other Flickr pages due to the lack of a key data on this page.

**3. For Issue 3:**
Enlarging user profile images can be a need for other users thus PhotoShow will not stop working for them on Flickr.

Cheers.

**Comment by decembre** [comment] 2024-03-24 11:45
Whouaa: work fine for Flickr now!

**Mini Thumbnail in Photo page and in popup of GM "Buddy interesting" in User Contact/ Follow page 
are available now.**

I appreciate a lot your fast update,
and the design and simplicity of  your addon
Thanks :-)

### **_About Issues 2A + 2B:_**
"Buddy avatar"
AND 
"Arrow near the buddy icon":
I understand and my workaround with CSS :has() work for me.

### Request:
I need :has selector because i can't distinguish your popup directly:
i need to select it if it has a particular image inside.


If your preview popup should have a ref to the image inside, it should be possible to select it directly.

Maybe it can be useful if you add a context menu to dismiss certain images?
I should be more easy... if your context menu "copy link image HD" work  ;-)

**Comment by Mr-VincentW** [comment] 2024-03-25 05:58
PhotoShow has a stable DOM structure for its popup, you can select the image inside it simply with a CSS selector like `#photoShowViewer img`.

Allowing custom passing-by rules requires a lot effort. PhotoShow is avoiding introducing complex new features at the moment since it's being refactored due to a request for chrome extension iteration.

The contextmenu item `Copy HD image address` works well for me, if you have problem with it, please open a new issue and attach more details, thanks.

**Comment by decembre** [comment] 2024-03-25 14:25
### For the "Copy HD link":
You are right, it's another extension which cause this problem.
I send a request to its dev:
<a href="https://www.flickr.com/groups/flickrhacks/discuss/72157655601688753/page2/#comment72157721920510956">Flickr Fixr - Multifeature browser extension for Flickr users</a>

### For "Allowing custom passing-by rules requires a lot effort":
I understand and i am the first which want to keep you extension simple to use
 :-)
I have notice the '#photoShowViewer img":
As i said before, this css selector is  not be able to hide the whole popup for unwanted preview of particular image.
When i hide just the image inside, the style of the popup remain visible (background / border / etc...)

That's because actually i need :has(), which is able to select the whole popup IF a particular image is inside it (and i can hide it).

If you add to the Popup an attribute which have the ref to this image, i can hide the popup without use :has() (only available for new browser).
Anyway, that's not very crucial, your addon work fine without it.

**Comment by Mr-VincentW** [comment] 2024-04-01 08:16
Based on the current implementation of PhotoShow, it's a bit complicated to add such an attribute to the popup. I'll reopen this issue for future reference and PhotoShow will likely allow users to customize blocking rules in its future versions.

**Comment by decembre** [comment] 2024-04-01 09:09
wait and see...
;-)

**Comment by decembre** [comment] 2024-08-08 16:17
Since the last update, some previews don't work all the time.
By example for the previous solved case:
4 - the mini-thumbnails, another Flickr thumbnail which not work (That the mini-thumbnails in the Photo page under the Photo.)
or Preview just one shot and after nothing ,
or preview always the same shot when i want preview another shot...
Another test link:
https://www.flickr.com/photos/worteinbildern/53892225037/in/photostream/

Another small problem:
The orientation sometime fail:
Test link (in the mini thumbnail the preview of this shot s badly rotated:
https://www.flickr.com/photos/biancatruzzi/32167428396/in/photostream/

**Comment by Mr-VincentW** [comment] 2024-08-10 04:05
Flickr seemed to have had some problems themselves recently, the link you attached didn't work for me yesterday either but started working well again from this morning.

The problem of always displaying the same HD image when you hovering over the thumbnails navigation bar will be solved with the next update of PhotoShow.

For the orientation issue, PhotoShow shows the original orientation of the images it gets, so it's still a problem of the image sources of Flickr. (I checked the link you attached, the image does have this issue for its largest version.)

Thank you.

**Comment by decembre** [comment] 2024-08-10 07:52
Thank for your quick reply:
Yes, Flickr was a "little" down:
<a href="https://www.flickr.com/help/forum/en-us/72157723008641253/">[Flickr Help Forum - Monitoring Fix] Question marks are back and issues with uploading</a>

But now it seems OK.

- Orientation issue:
Ha, yes, if Flickr fail, you can't do better ;-)
Re Edit:
(for info) I sent a request:
<a href="https://www.flickr.com/help/forum/en-us/72157723026607279/">Photo orientation sometime fail (flipped) [Flickr Help Forum</a>
-  Mini Thumbnail
And as i said, for the mini thumbnail, - i use it a lot - i don't have preview (very similar to the first time i post my request to you).
For you it's ok ?

**Comment by Mr-VincentW** [comment] 2024-08-11 00:20
- **Orientation issue:**
Actually PhotoShow can choose to display a smaller version of the images which has got the correct orientation but... hmmm, I think people would rather have the largest ones and the issue is not happening to every photo thank goodness.

- **Mini thumbnails:**
Are you saying you're not getting the preview for them as shown in the screenshot below?
![image](https://github.com/user-attachments/assets/fb3b3d33-a62a-4822-841e-718626a60884)

**Comment by decembre** [comment] 2024-08-11 01:31
Mini thumbnails:
Yes, it fail the most of the time.
And if it work, it display only one and not the others (exactly the same problem before you fixed it).
Test link:
https://www.flickr.com/photos/agedsenator/3561511535/in/faves-66818156@N08/
![Photoshow- PB Flickr Mini Thumbnail- request2 - GIF 11-08-2024 03-42-45](https://github.com/user-attachments/assets/78e935cc-7916-432e-bde7-2619cb44a8ed)

Orientation issue:
Yes, it's not often...
;-)

**Comment by Mr-VincentW** [comment] 2024-08-11 07:17
I noticed your thumbnails are way different from the original ones provided by Flickr, I assume it's from some third-party script? Please let me know how I can get the same thumbnails navigation like yours. Cheers.

**Comment by decembre** [comment] 2024-08-11 11:00
That's principally due to my userstyle:
<a href="https://userstyles.world/style/248/flickr-widescreen-bigone-v-301-usw">Flickr WideScreen - BigONE v.301 (USw)</a>
And as its name said, it's for a BIG screen (i hope you have one...)

And my userscript (which auto load more thumbnail in it):
<a href="https://greasyfork.org/fr/scripts/31560-flickr-auto-more-mini-thumbnail-in-photo-page-v-2-1-ok-exclude-2019">Flickr - AUTO More Mini Thumbnail in Photo page</a>
For the GIF screen it was disable...

**Comment by Mr-VincentW** [comment] 2024-08-12 08:19
I tried the **BigONE** styles and the **AUTO More Mini Thumbnail** script. PhotoShow still worked for me in this case. Although the HD images loaded are not the largest versions, which will be fixed with the next PhotoShow update, I could still get HD images.
![image](https://github.com/user-attachments/assets/b59bf020-8bad-4eb0-8acf-430903410307)

In your screenshot it looked more like there's some other style that made the whole thumbnails area invisible to mouse events (might caused by some **pointer-events: none** style), that's likely why instead of getting an HD image preview for each of the thumbnails, you got one for the whole thumbnail container. Please double check this.

Thanks.

**Comment by decembre** [comment] 2024-08-12 10:38
Thank Vincent for your all effort to find a problem where it was not your fault
:-)
Because after testing, I found the origin of the problem ( your mention of "pointer-events" helped me).
3 userscripts:
1 - <a href="https://greasyfork.org/fr/scripts/3511-enable-right-click-reek">Enable Right Click | Reek</a>
2 - <a href="https://greasyfork.org/fr/scripts/498955-%E4%BB%A5%E5%9B%BE%E6%90%9C%E5%9B%BE%E5%A2%9E%E5%BC%BA%E7%89%88/feedback">以图搜图增强版  - Version améliorée de la recherche d'images</a>
Last Re Edit (i hope...):
3 - **OR finally this OLD userscript which i use a lot too:**
Old page info with detailed screenshot:
<a href="https://userscripts-mirror.org/scripts/show/5016">Flickr Functional Suite By Charles Tilford — Last update Aug 4, 2006 [userscripts-mirror]</a>

Its description:
_"Provides an interface to let you assign colors to users you meet - that way, if you find a user's link on a page in the future, it will automatically be highlighted with thes color you previously gave them."_

A long time ago , its dev - Charles Tilford - updated graciously  for me and it work always for me.
But it need some adaptation in Tampermonkey.
In my test if i set:
**Ajouter des fonctions GM à "this" ou à la fenêtre on "OFF" (before it was on "ON")**
It seems not interfere with your addon

![Flick - PhotoShow PB - FFS - 2024-08-12_142546](https://github.com/user-attachments/assets/f6b04973-eed3-4e96-93d2-6fc5475480d8)

My backup of it:
<a href="https://pastebin.com/sT37T2Rq">GM - Flickr Functional Suite - NEW (by C. Tilford)</a>


I hope to have finally find the right origin of this problem.

Maybe something stay to do for me around my userstyle (and my userscript) for the mini thumbnail area which is not perfect / perfect:
by example i can't chose - with the arrows - how to fill it in an other direction (always fill forward)
but it work.

Anyway, thank again for your patience, Vincent:
I wait for your next release.

**Comment by decembre** [comment] 2024-08-12 19:36
Sorry, but finally i think it's randomly fail:
All my test work a moment and after don't work....

By example (always for Mini Thumbnail):
1 - I disable all my Userstyles.
Always the same PB

2 -  disable "[Flickr Functional Suite](https://userscripts-mirror.org/scripts/show/5016)":
PhotoShow work a couple of time and stop after
And after re enable it;
your addon work... waiting the next time it fail...

So, randomly problem, no ?

Now , in an other hand, my configuration is not different before your last update.
And before Photoshow worked fine.


OR ... Maybe it's a Flickr problem?
I see many famous "Bad Pandas" (Flickr's error pages) this last time...

Can i  help you by a console log ?

**Comment by decembre** [comment] 2024-08-14 02:37
Finally, after many tests,  i tested too to downgrading to a previous version of PhotoShow.
I tested v.4.36.0

AND......
All seems working fine!
;-)
I don't know why:
Have you an idea?

**Comment by Mr-VincentW** [comment] 2024-08-14 04:14
This sounds a bit tricky. Maybe it's worth trying -

1) Disable all other extensions/custom scripts/custom styles and test PhotoShow alone.
2) Check if any errors happen during your test on chrome://extensions/ with **developer mode** on. You might need to clear any existing errors and start a clean test.
![image](https://github.com/user-attachments/assets/08bf33d5-c544-4150-bed7-720143babea9)

Cheers.

**Comment by decembre** [comment] 2024-08-14 05:44
I created a new profile.
Close it.
Copy in it my Previous Profile files (after deleting the existing).
Delete all exentions.
Install Last Photoshow update.
With developer mode on, open the console.
Clear it and use Photosh on Mini Thumbnail.

It seems working, only fail on some shot (always in Mini Thumbnail).

Here some info found in it (copied from console):

[TEST PHOTSHOW ALONE.txt](https://github.com/user-attachments/files/16607981/TEST.PHOTSHOW.ALONE.txt)

**Comment by Mr-VincentW** [comment] 2024-08-14 06:08
The log looks fine.
The issue of getting frequent failures for mini thumbnails should be improved a bit with the next PhotoShow update. Though some of the cases are "**private images**" from Flickr which I assume either is paid content or another bug for Flickr.
Let's see how it goes when the next update of PhotoShow is released.
Thanks.

**Comment by decembre** [comment] 2024-08-14 08:53
:-)

**Comment by Mr-VincentW** [comment] 2024-08-19 05:31
PhotoShow has been updated to 4.41 which includs some optimizations for Flickr, please try it again to see if things get improved. Cheers.

**Comment by decembre** [comment] 2024-08-19 07:14
Sorry, Was happy but i haven't refreshed the extension page:

Now after a refresh, i tested  your last update:
Seems they are always problems for the Mini thumbnail....

Here some of my tests (with the previous version v.4.36.0):

1 - Mini Thumbnails:
Problems to preview "restricted" content.
Idem for other shots from user deleted which are only visible in this place (and with a trick which i don't remember now):
but for that i think you can't do something (that's a Flick bug).

**OTHER important PAGES:**

2 - **Albums list:**
Work.
But problem for restricted content:
- Test link (mine):
https://www.flickr.com/photos/bruno-decembre/albums
- Test link (Other user with restricted content):
https://www.flickr.com/photos/misu_1975/albums/
https://www.flickr.com/photos/fabiov1/albums/with/72157649742189375

3 - **Albums it self:**
Doesn't work...
- Test link (one of mine):
https://www.flickr.com/photos/bruno-decembre/albums/174533
- Test link (Other user with restricted content):
https://www.flickr.com/photos/fabiov1/albums/72157649742189375

4 - **Favoris:**
Work.
But problems to preview "restricted" content.
- Test link (mine with some restricted content):
https://www.flickr.com/photos/bruno-decembre/favorites
- Test link (other user with some restricted content):
https://www.flickr.com/photos/archi-bald/favorites

5  - **Galleries - Galleries List and Galleries:**
Work and should not have problem for "restricted" content:
They are prohibited in them.

6 - **Collections LIST:**
Work.
I don't have test link with "restricted" content now.
- Test Link (mine):
https://www.flickr.com/photos/bruno-decembre/collections
https://www.flickr.com/photos/bruno-decembre/collections/72157625128195679/

7 - **Collection it self:**
Doesn't work.
- Test link (mine)
https://www.flickr.com/photos/bruno-decembre/sets/174533/

8 - *Search:*
Work.
But problem for restricted content:
- Test link (normally without "restricted" content:
https://www.flickr.com/search/?text=portrait
- Test link with "restricted" content:
- https://www.flickr.com/search/?text=nudit%C3%A9

11 - **POOL:**
Note:
There are 2 Mods for them:
- BETA - aka Classic(deprecated) 
- NO BETA aka normal view
If it is easy to choose the **No Beta aka normal view**, by just clicking the link which ask to do that.
But not very easy to change from **NO BETA aka normal** to **BETA - aka Classic (deprecated)** 👍🏻 we need to go to the option in our profile and choose in "Privacy & Permissions" tabs:
"Switch to classic Groups (deprecated)"
For me, i stay with the Classic (deprecated):
As administrators i can chose a square view (which don't exist in the No Beta...)

Work for BETA view:
But in No Beta view, the restricted content are not displaying.

- Test link (one of mine with some "restricted"):
https://www.flickr.com/groups/portrait-faces-master-view/pool/?thumb=1

10 - **Help Forum:**
Work.
- Test link:
https://www.flickr.com/help/forum/en-us/72157723020257103/

11 - **Notifications:**
Work.
But problem for restricted content:
Link:
https://www.flickr.com/notifications

**Others pages (no often used by me):**
Seems all working.
- Tags:
https://www.flickr.com/photos/bruno-decembre/tags/debeurme/
- Explore:
https://www.flickr.com/explore/with/53930307713
- Fresh Uploads:
https://www.flickr.com/search/?text=&view_all=1&media=photos&content_type=1&dimension_search_mode=min&height=640&width=640&safe_search=2&sort=date-posted-desc&min_upload_date=1724041674

**Comment by decembre** [comment] 2024-08-19 11:01
Frankly i don't understand where is the problem:
I am lost, in fact.

Maybe i do something wrong, but i tested many options.

The last one, is to rebuild a new profile and import one by one my addons .
And use backup from Stylus and Tampermonkey to import them (userstyles and userscripts) to the new profile.

I refresh and go to my  Flickr page at each steps, to show if something goes wrong.

And each step, your addon (last updated) work.

And suddenly, it fail.
It's difficult to see why or when.

And not possible to go back at this step:
delete or disable addons don't change the problem.

I tested too to manually adding only 2 userscripts (Flickr Functionnal and Commented ON) for Flickr:
Work at each step.
Reload the profile:
Fail.
Delete the 2 scripts and reload the profile:
Fail.
Delete Tampermonkey and reload profile:
Fail.

The only way is to delete your addon,
and re-install it after.
So strange.....

**Comment by Mr-VincentW** [comment] 2024-08-29 04:17
Heaps of thanks for the comprehensive testing list for Flickr. I have updated PhotoShow to 4.42 which is optimized again for Flickr especially for restricted content. You may wanna try it your self.

Also, for the instability issue, if you're on Firefox, it's just normal... Sometimes you might need to reinstall related extensions or even the browser itself to make everything work again. If you're not, I'd be happy to help if more detailed guidance for reproducing the issue is provided.

**Comment by decembre** [comment] 2024-08-29 05:14
![PHOTOSHOW PB - Small preview on User Modal - 2024-08-29_074334](https://github.com/user-attachments/assets/4eba33ae-dcc7-45d3-b832-ce998f9030c3)

Hoo...., all worked fine a moment and stop working correctly suddenly.

i refreshed my extensions pages, search update, show your and go to a flickr photo page:
work fine.
I closed the browser.
Use CCleaner.

Reopen it:
all work fine too:
was happy... a moment.

After a short time your addon fail.
By example very small preview on the hover user buddy modal infos
and fail on this damn Mini Thumbnail.

Quick Test on an other profile dedicated to PhotoShow ( this profile without others add-ons than your).
Update / close profile / reopen it:
Same problems than this my principal profile.

Note:
Downgrading to the last Manifest v.2 version:
Work fine on photo page....

**Comment by Mr-VincentW** [comment] 2024-09-01 04:06
Another defect that could cause this issue has been identified and fixed in update 4.43. You might still wanna give it another go.
Good luck and thanks again for reporting these issues. 🙂

**Comment by decembre** [comment] 2024-09-01 11:20
YES!
All seems working perfectly now:
good job!
As usual i appreciate your attention to our request (mine in particular, with this damn Mini-Thumbnail).
;-)

**Comment by Mr-VincentW** [comment] 2024-09-01 11:33
You’re very welcome! I wouldn't have been able to figure out this tricky issue without your help, really appreciate it.

**Comment by Mr-VincentW** [comment] 2024-10-27 12:24
> If you add to the Popup an attribute which have the ref to this image, i can hide the popup without use :has() (only available for new browser).

PhotoShow has introduced an experimental feature in update **4.49** to address this. As shown in the screenshot below, a `data-thumbnail-selector` attribute has been added to the outermost viewer container, referencing the source thumbnail element currently displayed. You can now select the source thumbnail element using this selector string.
![image](https://github.com/user-attachments/assets/3fc0e74f-753a-4591-ad59-b1310cc839dd)

Here are some additional notes:

- The source thumbnail element referenced by this selector isn’t always an image; it could also be any element with a background image, an SVG, a video, a link, an ancestor element of another image, or even any random element, depending on the site.
- The selector doesn’t cross iframes, meaning it only works within the frame where the thumbnail element resides. Fortunately, on most sites, there is minimal visible content within subframes.
- The selector does cross open Shadow DOM boundaries, with shadow roots separated by `/` in the selector. For instance, a selector like `#some-id>some-tag-name/a-shadow-dom-element/another-shadow-dom-element>img` can be located with the attached code.
```
document
  .querySelector('#photoShowViewer')
  .dataset.thumbnailSelector.split('/')
  .reduce((queryRoot, selector) => (queryRoot.shadowRoot || queryRoot).querySelector(selector), document);
```

I hope this helps! Feel free to continue the discussion or reopen the issue if needed. Cheers!

**Closed as completed by Mr-VincentW** 2024-10-27 12:24 UTC
Labels: VIP
